### ISSUE TITLE
Pass arguments to electron-packaged app to be passed to zcoind

### ISSUE THREAD

**Issue by riordant** [firoorg/firo-client#111]
As we can do with `zcoin-qt` currently, users should be able to pass zcoind conf arguments directly to the client executable. This appears to be quite possible: https://stackoverflow.com/questions/49552703/passing-command-line-arguments-to-electron-executable-after-installing-an-alrea

**Comment by sproxet** [comment]
The `setargsfornextrun` Debug Console command and `FIROD_ARGS` environment variable accomplish this.
