### ISSUE TITLE
Suggestion: Znode Setup Wizard

### ISSUE THREAD

**Issue by catchingknives** [firoorg/firo-client#13]
Suggestion for later version:

In absence of znode.conf and if XZC > 1,000, show setup wizard button on Znode tab.

Possible workflow:
1. Add IPs and labels (save no. of Znodes as variable)
2. Generate key(s) (depending on no. of Znodes)
3. Create address(es)
4. Suggest to make collateral transaction (option to copy address to DIY)
5. Finish, save znode.conf (if using 3rd party hoster)

Rough idea. Suggestions welcome!

Mockup:
![Znode Setup Wizard Mockup](https://i.imgur.com/NkdhZId.png)

**Comment by qashban4** [comment]
This issue is down prioritized as it can be done via console and master nodes are being reworked soon
