### ISSUE TITLE
Empty 'Zcoin Client' folder still created in AppData\Roaming

### ISSUE THREAD

**Issue by justanwar** [firoorg/firo-client#135]
To reproduce:
Close running zcoin-client. Delete `Zcoin Client` folder in `AppData\Roaming`. Start zcoin-client. The folder is recreated.

**Comment by sproxet** [comment]
This is the result of an Electron misfeature that's been corrected in https://github.com/electron/electron/pull/17841 We'll need to upgrade Electron to fix it.
