### ISSUE TITLE
ZCoin client frozen

### ISSUE THREAD

**Issue by hakonamatata** [firoorg/firo-client#140]
Tried opening zcoin-client with a wallet that does not have a password. The client just hangs. 

![zcoin-frozen](https://user-images.githubusercontent.com/4003969/87883593-c90f6580-ca08-11ea-9959-f4459094e637.gif)

**Comment by hakonamatata** [comment]
Can I also add, that there is no consistency in the "rounded corners" design. The buttons does not have rounded corners and no spacing between them. The main window does not have rounded corners, but the container box does, and way to much.

**Comment by sproxet** [comment]
Hi, unfortunately I was unable to reproduce this issue. Can you delete your zcoin-client.log, open the client as before in order to induce the error, and then upload its contents? On Windows, the file should be located at `%APPDATA\zcoin-client\zcoin-client.log`.
