### ISSUE TITLE
Electron Wallet - Stuck at block 313022

### ISSUE THREAD

**Issue by afosterr** [firoorg/firo-client#156]
Hi, I am currently syncing my Electron wallet and I'm stuck at block 313022.
![Capture d’écran (2687)](https://user-images.githubusercontent.com/79528029/108979956-1761a280-7683-11eb-941f-93c84c57bdf5.png)

**Comment by justanwar** [comment]
The new rebranded Electron wallet is currently in the final stages of testing. [Please use the QT one in the meantime. ](https://github.com/firoorg/firo/releases)

**Comment by afosterr** [comment]
Ok thanks.

**Comment by BogdanTheGeek** [comment]
mine is stuck at 281234, QT also doesn't work and keep crashing. I do have enough storage.

**Comment by reubenyap** [comment]
Try this new version: https://github.com/firoorg/firo-client/releases/tag/v2.0.0-beta
